# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Chat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'RxAlamofire'
    pod 'ObjectMapper'
    pod 'AlamofireObjectMapper'
    pod 'RxCocoa', '~> 3.0'
    pod 'RxDataSources', '~> 1.0'
    pod 'RealmSwift'
    pod 'Realm'
    pod 'RxRealm'
    pod 'SWTableViewCell', '~> 0.3.7'
    pod 'Kingfisher', '~> 3.0'
  target 'ChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
